"""initial graph schema

Revision ID: c636e4be00a5
Revises:
Create Date: 2026-07-02 10:35:37.890604
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "c636e4be00a5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conflicts",
        sa.Column(
            "conflict_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("entity_kind", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("resolution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_kind IN ('work', 'version', 'edge')", name=op.f("ck_conflicts_entity_kind")
        ),
        sa.CheckConstraint("status IN ('open', 'resolved')", name=op.f("ck_conflicts_status")),
        sa.PrimaryKeyConstraint("conflict_id", name=op.f("pk_conflicts")),
    )
    op.create_index(
        "ix_conflicts_entity", "conflicts", ["entity_kind", "entity_id", "status"], unique=False
    )
    op.create_table(
        "edges",
        sa.Column(
            "edge_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("edge_type", sa.Text(), nullable=False),
        sa.Column("src_kind", sa.Text(), nullable=False),
        sa.Column("src_id", sa.Uuid(), nullable=False),
        sa.Column("dst_kind", sa.Text(), nullable=False),
        sa.Column("dst_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("human_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(edge_type IN ('is_remake_of', 'is_official_dub_of', 'is_unofficial_remake_of')"
            " AND src_kind = 'version' AND dst_kind = 'version')"
            " OR (edge_type IN ('is_sequel_of', 'based_on')"
            " AND src_kind = 'work' AND dst_kind = 'work')",
            name=op.f("ck_edges_type_shape"),
        ),
        sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM')", name=op.f("ck_edges_confidence")),
        sa.CheckConstraint("dst_kind IN ('version', 'work')", name=op.f("ck_edges_dst_kind")),
        sa.CheckConstraint(
            "edge_type IN ('is_remake_of', 'is_official_dub_of', 'is_unofficial_remake_of',"
            " 'is_sequel_of', 'based_on')",
            name=op.f("ck_edges_edge_type"),
        ),
        sa.CheckConstraint("src_kind IN ('version', 'work')", name=op.f("ck_edges_src_kind")),
        sa.CheckConstraint("src_id <> dst_id", name=op.f("ck_edges_no_self_edge")),
        sa.PrimaryKeyConstraint("edge_id", name=op.f("pk_edges")),
        sa.UniqueConstraint("edge_type", "src_id", "dst_id", name="uq_edges_edge_type_src_dst"),
    )
    op.create_index("ix_edges_dst_id", "edges", ["dst_id"], unique=False)
    op.create_index("ix_edges_src_id", "edges", ["src_id"], unique=False)
    op.create_table(
        "person",
        sa.Column(
            "person_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("wikidata_qid", sa.Text(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("person_id", name=op.f("pk_person")),
        sa.UniqueConstraint("wikidata_qid", name=op.f("uq_person_wikidata_qid")),
    )
    op.create_table(
        "work",
        sa.Column(
            "work_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("work_type", sa.Text(), nullable=False),
        sa.Column("primary_title", sa.Text(), nullable=False),
        sa.Column("original_language", sa.Text(), nullable=True),
        sa.Column("first_release_year", sa.Integer(), nullable=True),
        sa.Column("wikidata_qid", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("human_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM')", name=op.f("ck_work_confidence")),
        sa.CheckConstraint(
            "work_type IN ('film', 'literary_source')", name=op.f("ck_work_work_type")
        ),
        sa.PrimaryKeyConstraint("work_id", name=op.f("pk_work")),
        sa.UniqueConstraint("wikidata_qid", name=op.f("uq_work_wikidata_qid")),
    )
    op.create_table(
        "version",
        sa.Column(
            "version_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("wikidata_qid", sa.Text(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("is_original", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("confidence", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("human_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("confidence IN ('HIGH', 'MEDIUM')", name=op.f("ck_version_confidence")),
        sa.ForeignKeyConstraint(
            ["work_id"], ["work.work_id"], name=op.f("fk_version_work_id_work")
        ),
        sa.PrimaryKeyConstraint("version_id", name=op.f("pk_version")),
        sa.UniqueConstraint("wikidata_qid", name=op.f("uq_version_wikidata_qid")),
    )
    op.create_index(op.f("ix_version_imdb_id"), "version", ["imdb_id"], unique=False)
    op.create_index(op.f("ix_version_tmdb_id"), "version", ["tmdb_id"], unique=False)
    op.create_index(op.f("ix_version_work_id"), "version", ["work_id"], unique=False)
    op.create_table(
        "candidate_edges",
        sa.Column(
            "candidate_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("edge_type", sa.Text(), nullable=False),
        sa.Column("src_version_id", sa.Uuid(), nullable=True),
        sa.Column("dst_version_id", sa.Uuid(), nullable=True),
        sa.Column("src_title_raw", sa.Text(), nullable=True),
        sa.Column("dst_title_raw", sa.Text(), nullable=True),
        sa.Column("supporting_sentence", sa.Text(), nullable=False),
        sa.Column("source_page", sa.Text(), nullable=False),
        sa.Column("source_revision", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("model_confidence", sa.Float(), nullable=True),
        sa.Column("extraction_run", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'proposed'"), nullable=False),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_edge_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "edge_type IN ('is_remake_of', 'is_official_dub_of', 'is_unofficial_remake_of',"
            " 'is_sequel_of', 'based_on')",
            name=op.f("ck_candidate_edges_edge_type"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'confirmed', 'rejected')",
            name=op.f("ck_candidate_edges_status"),
        ),
        sa.ForeignKeyConstraint(
            ["dst_version_id"],
            ["version.version_id"],
            name=op.f("fk_candidate_edges_dst_version_id_version"),
        ),
        sa.ForeignKeyConstraint(
            ["promoted_edge_id"],
            ["edges.edge_id"],
            name=op.f("fk_candidate_edges_promoted_edge_id_edges"),
        ),
        sa.ForeignKeyConstraint(
            ["src_version_id"],
            ["version.version_id"],
            name=op.f("fk_candidate_edges_src_version_id_version"),
        ),
        sa.PrimaryKeyConstraint("candidate_id", name=op.f("pk_candidate_edges")),
    )
    op.create_table(
        "plot_texts",
        sa.Column(
            "plot_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("revision_id", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("source IN ('wikipedia', 'tmdb')", name=op.f("ck_plot_texts_source")),
        sa.ForeignKeyConstraint(
            ["version_id"], ["version.version_id"], name=op.f("fk_plot_texts_version_id_version")
        ),
        sa.PrimaryKeyConstraint("plot_id", name=op.f("pk_plot_texts")),
    )
    op.create_index(op.f("ix_plot_texts_version_id"), "plot_texts", ["version_id"], unique=False)
    op.create_table(
        "version_cast",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("role_kind", sa.Text(), nullable=False),
        sa.Column("billing_order", sa.Integer(), nullable=True),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "role_kind IN ('lead', 'support', 'director')", name=op.f("ck_version_cast_role_kind")
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["person.person_id"], name=op.f("fk_version_cast_person_id_person")
        ),
        sa.ForeignKeyConstraint(
            ["version_id"], ["version.version_id"], name=op.f("fk_version_cast_version_id_version")
        ),
        sa.PrimaryKeyConstraint(
            "version_id", "person_id", "role_kind", name=op.f("pk_version_cast")
        ),
    )
    op.create_table(
        "version_title",
        sa.Column(
            "title_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("match_key", sa.Text(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "kind IN ('canonical', 'aka', 'dub', 'transliteration')",
            name=op.f("ck_version_title_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"], ["version.version_id"], name=op.f("fk_version_title_version_id_version")
        ),
        sa.PrimaryKeyConstraint("title_id", name=op.f("pk_version_title")),
    )
    op.create_index("ix_version_title_match_key", "version_title", ["match_key"], unique=False)
    op.create_index(
        op.f("ix_version_title_version_id"), "version_title", ["version_id"], unique=False
    )
    # ### end Alembic commands ###

    # --- Polymorphic-FK hardening (DEC-P1-1): edge endpoints must exist in the table named ---
    # --- by src_kind/dst_kind. Constraint trigger = deferred-capable, fires per row.       ---
    # (Pipeline is upsert-only; delete-side guards are out of scope until a delete flow exists.)
    op.execute(
        """
        CREATE FUNCTION edges_endpoints_exist() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF NEW.src_kind = 'version' THEN
                IF NOT EXISTS (SELECT 1 FROM version WHERE version_id = NEW.src_id) THEN
                    RAISE EXCEPTION 'edges.src_id % not found in version', NEW.src_id
                        USING ERRCODE = 'foreign_key_violation';
                END IF;
            ELSIF NOT EXISTS (SELECT 1 FROM work WHERE work_id = NEW.src_id) THEN
                RAISE EXCEPTION 'edges.src_id % not found in work', NEW.src_id
                        USING ERRCODE = 'foreign_key_violation';
            END IF;
            IF NEW.dst_kind = 'version' THEN
                IF NOT EXISTS (SELECT 1 FROM version WHERE version_id = NEW.dst_id) THEN
                    RAISE EXCEPTION 'edges.dst_id % not found in version', NEW.dst_id
                        USING ERRCODE = 'foreign_key_violation';
                END IF;
            ELSIF NOT EXISTS (SELECT 1 FROM work WHERE work_id = NEW.dst_id) THEN
                RAISE EXCEPTION 'edges.dst_id % not found in work', NEW.dst_id
                        USING ERRCODE = 'foreign_key_violation';
            END IF;
            RETURN NEW;
        END $$;
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER edges_endpoints_exist
        AFTER INSERT OR UPDATE ON edges
        FOR EACH ROW EXECUTE FUNCTION edges_endpoints_exist();
        """
    )

    # --- The verification gate as schema (P1_SPEC §1.8; MEDIUM-passes clarification logged ---
    # --- in DECISIONS.md): a row is ground truth only if its sources[] is non-empty AND it  ---
    # --- has no open conflict. CANDIDATE tier is excluded by construction (separate table). ---
    op.execute(
        """
        CREATE VIEW ground_truth_works AS
        SELECT w.* FROM work w
        WHERE jsonb_array_length(w.sources) > 0
          AND NOT EXISTS (
              SELECT 1 FROM conflicts c
              WHERE c.entity_kind = 'work' AND c.entity_id = w.work_id AND c.status = 'open');
        """
    )
    op.execute(
        """
        CREATE VIEW ground_truth_versions AS
        SELECT v.* FROM version v
        WHERE jsonb_array_length(v.sources) > 0
          AND NOT EXISTS (
              SELECT 1 FROM conflicts c
              WHERE c.entity_kind = 'version' AND c.entity_id = v.version_id
                AND c.status = 'open');
        """
    )
    op.execute(
        """
        CREATE VIEW ground_truth_edges AS
        SELECT e.* FROM edges e
        WHERE jsonb_array_length(e.sources) > 0
          AND NOT EXISTS (
              SELECT 1 FROM conflicts c
              WHERE c.entity_kind = 'edge' AND c.entity_id = e.edge_id AND c.status = 'open');
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS ground_truth_edges")
    op.execute("DROP VIEW IF EXISTS ground_truth_versions")
    op.execute("DROP VIEW IF EXISTS ground_truth_works")
    op.execute("DROP TRIGGER IF EXISTS edges_endpoints_exist ON edges")
    op.execute("DROP FUNCTION IF EXISTS edges_endpoints_exist()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_version_title_version_id"), table_name="version_title")
    op.drop_index("ix_version_title_match_key", table_name="version_title")
    op.drop_table("version_title")
    op.drop_table("version_cast")
    op.drop_index(op.f("ix_plot_texts_version_id"), table_name="plot_texts")
    op.drop_table("plot_texts")
    op.drop_table("candidate_edges")
    op.drop_index(op.f("ix_version_work_id"), table_name="version")
    op.drop_index(op.f("ix_version_tmdb_id"), table_name="version")
    op.drop_index(op.f("ix_version_imdb_id"), table_name="version")
    op.drop_table("version")
    op.drop_table("work")
    op.drop_table("person")
    op.drop_index("ix_edges_src_id", table_name="edges")
    op.drop_index("ix_edges_dst_id", table_name="edges")
    op.drop_table("edges")
    op.drop_index("ix_conflicts_entity", table_name="conflicts")
    op.drop_table("conflicts")
    # ### end Alembic commands ###
